# Generated by Django 3.0.2 on 2020-01-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sniping_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
