# Generated by Django 3.0.2 on 2020-01-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sniping_site', '0002_show_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='date',
        ),
        migrations.RemoveField(
            model_name='show',
            name='time',
        ),
        migrations.AddField(
            model_name='show',
            name='entrytime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='showtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
